server:
  port: 8080
  servlet:
    context-path: /web

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: webHitech
  datasource:
    url: jdbc:postgresql://localhost:5432/webhitech
    username: postgres
    password: harkins
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        timeout: 5m
      chat:
        options:
          model: mistral
        model: llama3
      embedding:
        model: nomic-embed-text

      vectorstore:
        pgvector:
          initialize-schema: true  # Đảm bảo schema được khởi tạo
          database: webhitech
          host: localhost
          port: 5432
          username: postgres
          password: harkins
          schema: public  # Chỉ định schema rõ ràng
          table: ai_vector_store  # Đặt tên bảng cụ thể
          embedding-dimension: 1536  # Kích thước của embedding vectors
          create-table-if-not-exists: true  # Đảm bảo bảng được tạo nếu chưa tồn tại

logging:
  level:
    org:
      springframework:
        ai:
          vectorstore: DEBUG
        jdbc:
          core: DEBUG  # Bật log chi tiết cho JDBC để xem các câu SQL

jwt:
  signerKey: "Ftbzo3IFNUZ/gqQhbF7/30/aoOASmg85tzSH/CCNA3XPyxbsi5RuywG/el7iIesc"
  valid-duration: 3600
  refreshable-duration: 14400

# ZaloPay configuration
zalopay:
  appId: 2554
  key1: sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn
  key2: trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
  endpoint: https://sb-openapi.zalopay.vn/v2/create
  orderstatus: https://sb-openapi.zalopay.vn/v2/query
  callback-url: https://1ac8-42-113-215-72.ngrok-free.app/zalopay/callback
  returnUrl: http://yourdomain.com/payment/zalopay-return

momo:
  partnerCode: MOMO
  returnUrl: http://localhost:3000/
  endpoint: https://test-payment.momo.vn/v2/gateway/api/
  ipnUrl: http://localhost:8080/web/momo/ipn-handler
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  notifyUrl: http://yourdomain.com/payment/momo-notify
  requestType: captureWallet

vnpay:
  endpoint: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmnCode: YOUR_VNPAY_TMN_CODE
  hashSecret: YOUR_VNPAY_HASH_SECRET
  returnUrl: http://yourdomain.com/payment/vnpay-return

mb:
  bank:
    endpoint: https://api.mb.com.vn/qr/generate
  accountNumber: YOUR_MB_BANK_ACCOUNT_NUMBER

